title: harishsarma_v
description: <p> Hey There! <a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" data-target="animated-image.originalLink"><img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" alt="hi" style="width: 25px; display: inline-block;" data-target="animated-image.originalImage"></a> I'm Harish Sarma from <img alt="India" width="20" src="https://emoji.discadia.com/emojis/87616d51-5ea9-4da5-a19e-e01ea8b6d08f.GIF">, a lover of all things creative and adventurous. I enjoy exploring new places, learning new things , and meeting new people. In my free time, you can find me practicing yoga <img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People%20with%20activities/Man%20Cartwheeling%20Medium-Light%20Skin%20Tone.png" 
alt="Man Cartwheeling Medium-Light Skin Tone" 
width="20" 
height="20" />, reading a good book <img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Books.png" 
alt="Books"
width="20" 
height="20" />, hang out with my friends <img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Grinning%20Face%20with%20Smiling%20Eyes.png" 
alt="Grinning Face with Smiling Eyes" 
width="20" 
height="20" />, playing games ğŸ® or watching a movie ğŸ¿.</p> 

<p> I'm excited to connect with like-minded individuals and share experiences. <br> Let's connect and get to know each other! </p>

author:
  name: Harish sarma
  url: https://harishsarmav.github.io/harishsarma_v/

owner: harishsarma_v
year: 2023

#title: harishsarma_v
#description: Welcome to my page!
#show_downloads: false
#google_analytics:
#theme: jekyll-
#comments: false 
